name: Static Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  phpstan:
    name: PHPStan (Level 6)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: none
          tools: composer:v2
      
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-phpstan-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-phpstan-
      
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress
      
      - name: Run PHPStan
        run: vendor/bin/phpstan analyze --no-progress --error-format=github
      
      - name: Report success
        if: success()
        run: echo "✅ PHPStan analysis passed (Level 6)"
  
  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: composer:v2
      
      - name: Validate composer.json
        run: composer validate --strict --no-check-lock
      
      - name: Report success
        if: success()
        run: echo "✅ composer.json is valid"

